version: '2.0'

networks:
  game_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.91.0.0/16

services:
  mongo:
    image: 'mongo:3.4.4'
    ports:
      - '127.0.0.1:27017:27017'
    networks:
      game_network:
        aliases:
          - db

  phaserquest:
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    image: ctftraining/starctf_2019_996game
    command: pm2-runtime /root/processes.yml
    ports:
      - '127.0.0.1:8081:8081'
    environment:
      - FLAG=flag{test_flag}
    networks:
      game_network:
        aliases:
          - web
volumes:
  mongo:
